name: Build (Android)

on:
  push:
     branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:
  build:
    
    name: Build Android
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 12
      uses: actions/setup-java@v2
      with:
        java-version: '12'
        distribution: 'adopt'
        
    - name: Cache Gradle and wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant Permission to Execute
      run: chmod +x gradlew
      
    - name: 🏗 Build with Gradle 🛠️
      run: ./gradlew build
